version: '3.1'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - /mnt/user0/portainer/teamcity-volume/buildserver_pgdata:/var/lib/postgresql/data

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8111:8111"  # Cambiado para usar el puerto 8111 directamente
    volumes:
      - /mnt/user0/portainer/teamcity-volume/data_dir:/data/teamcity_server/datadir
      - /mnt/user0/portainer/teamcity-volume/teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent-1:
    image: iskrudo/teamcity-agent-9.0:${TEAMCITY_VERSION}
    privileged: true
    deploy:
      replicas: 3
    volumes:
      - /mnt/user0/portainer/teamcity-volume/agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://teamcity:8111
    depends_on:
      - teamcity